/* 为了防止任何可能出现的数据丢失问题，您应该先仔细检查此脚本，然后再在数据库设计器的上下文之外运行此脚本。*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.WCFLog
	(
	ID bigint NOT NULL IDENTITY (1, 1),
	[Level] varchar(50) NULL,
	Date datetime NULL,
	Thread varchar(50) NULL,
	Logger varchar(50) NULL,
	Message varchar(4000) NULL,
	Exception varchar(2000) NOT NULL,
	Operation varchar(500) NOT NULL,
	Action varchar(500) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.WCFLog ADD CONSTRAINT
	PK_WCFLog PRIMARY KEY CLUSTERED 
	(
	ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.WCFLog SET (LOCK_ESCALATION = TABLE)
GO
COMMIT